# Generated by Django 4.2.7 on 2023-11-11 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctor_speciality'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='ordered_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors.services'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.CharField(choices=[('2023/11/11', '2023/11/11'), ('2023/11/12', '2023/11/12'), ('2023/11/13', '2023/11/13'), ('2023/11/14', '2023/11/14'), ('2023/11/15', '2023/11/15'), ('2023/11/16', '2023/11/16'), ('2023/11/18', '2023/11/18'), ('2023/11/19', '2023/11/19'), ('2023/11/20', '2023/11/20'), ('2023/11/21', '2023/11/21'), ('2023/11/22', '2023/11/22'), ('2023/11/23', '2023/11/23'), ('2023/11/25', '2023/11/25'), ('2023/11/26', '2023/11/26'), ('2023/11/27', '2023/11/27'), ('2023/11/28', '2023/11/28'), ('2023/11/29', '2023/11/29'), ('2023/11/30', '2023/11/30'), ('2023/12/02', '2023/12/02'), ('2023/12/03', '2023/12/03'), ('2023/12/04', '2023/12/04'), ('2023/12/05', '2023/12/05'), ('2023/12/06', '2023/12/06'), ('2023/12/07', '2023/12/07'), ('2023/12/09', '2023/12/09'), ('2023/12/10', '2023/12/10'), ('2023/12/11', '2023/12/11')]),
        ),
    ]
