# Generated by Django 4.2.7 on 2023-11-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_speciality_price_remove_speciality_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.speciality')),
            ],
        ),
    ]
